import { Schema } from "effect"

export const PredicateType = Schema.Literal(
  // Primary Creative (Artist -> Work)
  "composer",
  "lyricist",
  "writer",
  "librettist",
  "scriptwriter",
  "adapter",
  "translator",
  "revised by",
  "reconstructed by",
  "previous attribution",
  // Performance (Artist -> Recording/Release)
  "performer",
  "instrument",
  "vocal",
  "performing orchestra",
  "conductor",
  "chorus master",
  "concertmaster",
  "audio director",
  // Arrangement & Orchestration
  "arranger",
  "instrument arranger",
  "vocal arranger",
  "orchestrator",
  // Production & Engineering (Artist -> Recording/Release)
  "producer",
  "engineer",
  "audio",
  "mastering",
  "sound",
  "mix",
  "recording",
  "field recordist",
  "programming",
  "editor",
  "balance",
  "sound effects",
  "lacquer cut",
  // Remixing & Compilation
  "remixer",
  "mix-DJ",
  "compiler",
  "samples from artist",
  // Visual & Video
  "video director",
  "cinematographer",
  "animation",
  "choreographer",
  "video appearance",
  // Design & Visual Arts
  "artwork",
  "design",
  "graphic design",
  "illustration",
  "design/illustration",
  "photography",
  "art direction",
  "creative direction",
  "booklet editor",
  "liner notes",
  // Organizational (Artist -> Artist)
  "member of band",
  "subgroup",
  "collaboration",
  "tribute",
  "artist rename",
  "founder",
  "supporting musician",
  "vocal supporting musician",
  "instrumental supporting musician",
  "is person",
  "voice actor",
  // Leadership & Positions
  "artistic director",
  "conductor position",
  "composer-in-residence",
  "teacher",
  // Personal Relationships (Artist -> Artist)
  "parent",
  "sibling",
  "married",
  "involved with",
  // Business & Legal (Artist -> Label)
  "recording contract",
  "label founder",
  "owner",
  "personal label",
  "producer position at",
  "engineer position at",
  "executive position at",
  "creative position at",
  "artists and repertoire",
  "artists and repertoire position at",
  "position at",
  // Rights & Legal
  "copyright",
  "phonographic copyright",
  "video copyright",
  "publishing",
  "personal publisher",
  "licensor",
  "legal representation",
  // Geographic (Artist -> Area)
  "area",
  "begin-area",
  "end-area",
  // Miscellaneous Credits
  "misc",
  "booking",
  "production coordinator",
  "instrument technician",
  "commissioned",
  "dedication",
  "dedicated to",
  "premiere",
  "transfer",
  // Named After Relationships
  "named after artist",
  "named after label",
  "named after release group",
  "named after work",
  // Genre Relationship
  "artist-genre",
  // KEXP-specific predicates
  "played_on",
  "has_recording",
  "has_artist",
  "has_release",
  "has_label"
)

export type PredicateType = Schema.Schema.Type<typeof PredicateType>
